spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
  datasource:
    initialization-mode: always
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hotel_db
    username: manager
    password: ENC(7uo04J4idVPWlWJTL0WdL2qdWlDNCHI2)
jasypt:
  encryptor:
    password: hotel-db-secret
security:
  oauth2:
    client:
      clientId: 1b9a58c9a58fa46488c9
      clientSecret: 8c354d9f9f395b5f8a0662e6988b19858779d60a
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
logging:
  level:
    root: INFO
server:
  port: 5000
  servlet:
    context:
      path: /auth

---

spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: never
    url: jdbc:mysql://spring-hotel-db.cikshrwl8xnu.eu-west-2.rds.amazonaws.com:3306/hotel_db
    username: manager
    password: ENC(Db/39HzMqcbPZjf5V0h8iTxAfOjb0xBC)
jasypt:
  encryptor:
    password: aws-hotel-db-secret
