CREATE TABLE ROOM(
  ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  ROOM_NUMBER CHAR(2) NOT NULL UNIQUE,
  BED_INFO CHAR(2) NOT NULL
);

CREATE TABLE GUEST(
  GUEST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(32),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24)
);

CREATE TABLE RESERVATION(
  RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID BIGINT NOT NULL,
  GUEST_ID BIGINT NOT NULL,
  RES_DATE DATE
);

CREATE TABLE PROFANITY(
  PROFANITY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  WORD VARCHAR(64) NOT NULL
);

CREATE TABLE PROFANITYSET(
  PROFANITYSET_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL
);

CREATE TABLE PROFANITYSETWORDS(
  PROFANITYSETWORDS_ID BIGINT AUTO_INCREMENT PRIMARY KEY
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID);
ALTER TABLE PROFANITYSETWORDS ADD FOREIGN KEY (PROFANITYSET_ID) REFERENCES PROFANITYSET(PROFANITYSET_ID);
ALTER TABLE PROFANITYSETWORDS ADD FOREIGN KEY (PROFANITY_ID) REFERENCES PROFANITY(PROFANITY_ID);
CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);
